-- 005_create_learning_resources_table.sql
--
-- Admin-curated learning resources, matching the JKUAT proposal's
-- "Zero Hallucination Guardrails" requirement (FR-03): resource
-- suggestions must be queried from a verified database, never
-- generated by an LLM. This table is that verified database. It
-- starts empty -- there is no seed data here, because inventing
-- plausible-looking course names/URLs would be exactly the
-- hallucination problem this table exists to prevent. Populate it
-- by hand, with real, checked links, via the Supabase dashboard or a
-- future admin UI.
--
-- Every skill without a curated entry here still gets a resource
-- suggestion -- see src/reskilling/resources.py's deterministic
-- search-link fallback -- but it is visually and structurally
-- distinguished ("curated" vs "search") rather than presented with
-- false authority.

create table if not exists learning_resources (
    id          bigint generated always as identity primary key,
    skill_id    text not null,
    title       text not null,
    url         text not null,
    provider    text not null,
    is_free     boolean not null default true,
    created_at  timestamptz not null default now()
);

create index if not exists idx_learning_resources_skill on learning_resources(skill_id);

alter table learning_resources enable row level security;

-- Public read -- this is reference data with no per-user sensitivity,
-- and needs to be visible on the anonymous demo path's roadmap too,
-- not just to signed-in users.
create policy "Learning resources are readable by anyone"
    on learning_resources for select
    using (true);

-- No client-side write policy -- curation happens via the Supabase
-- dashboard directly, or a future admin-only endpoint using the
-- service-level connection, matching the same pattern as role changes
-- in 004_create_profiles_table.sql.
